/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardSalesIndexRouteImport } from './routes/dashboard/sales/index'
import { Route as DashboardRolesIndexRouteImport } from './routes/dashboard/roles/index'
import { Route as DashboardRestaurantIndexRouteImport } from './routes/dashboard/restaurant/index'
import { Route as DashboardDishesIndexRouteImport } from './routes/dashboard/dishes/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PublicAuthBetterAuthRouteImport } from './routes/_public/auth/better-auth'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSalesIndexRoute = DashboardSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRolesIndexRoute = DashboardRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardRestaurantIndexRoute =
  DashboardRestaurantIndexRouteImport.update({
    id: '/restaurant/',
    path: '/restaurant/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardDishesIndexRoute = DashboardDishesIndexRouteImport.update({
  id: '/dishes/',
  path: '/dishes/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthBetterAuthRoute = PublicAuthBetterAuthRouteImport.update({
  id: '/auth/better-auth',
  path: '/auth/better-auth',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/table': typeof DemoTableRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/better-auth': typeof PublicAuthBetterAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/dashboard/dishes/': typeof DashboardDishesIndexRoute
  '/dashboard/restaurant/': typeof DashboardRestaurantIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/table': typeof DemoTableRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/better-auth': typeof PublicAuthBetterAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/dashboard/dishes': typeof DashboardDishesIndexRoute
  '/dashboard/restaurant': typeof DashboardRestaurantIndexRoute
  '/dashboard/roles': typeof DashboardRolesIndexRoute
  '/dashboard/sales': typeof DashboardSalesIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/table': typeof DemoTableRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/auth/better-auth': typeof PublicAuthBetterAuthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/dashboard/dishes/': typeof DashboardDishesIndexRoute
  '/dashboard/restaurant/': typeof DashboardRestaurantIndexRoute
  '/dashboard/roles/': typeof DashboardRolesIndexRoute
  '/dashboard/sales/': typeof DashboardSalesIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/table'
    | '/dashboard/'
    | '/auth/better-auth'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/dashboard/dishes/'
    | '/dashboard/restaurant/'
    | '/dashboard/roles/'
    | '/dashboard/sales/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/table'
    | '/'
    | '/dashboard'
    | '/auth/better-auth'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/dashboard/dishes'
    | '/dashboard/restaurant'
    | '/dashboard/roles'
    | '/dashboard/sales'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/_public'
    | '/dashboard'
    | '/_public/about'
    | '/demo/better-auth'
    | '/demo/convex'
    | '/demo/table'
    | '/_public/'
    | '/dashboard/'
    | '/_public/auth/better-auth'
    | '/api/auth/$'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/dashboard/dishes/'
    | '/dashboard/restaurant/'
    | '/dashboard/roles/'
    | '/dashboard/sales/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoTableRoute: typeof DemoTableRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sales/': {
      id: '/dashboard/sales/'
      path: '/sales'
      fullPath: '/dashboard/sales/'
      preLoaderRoute: typeof DashboardSalesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/roles/': {
      id: '/dashboard/roles/'
      path: '/roles'
      fullPath: '/dashboard/roles/'
      preLoaderRoute: typeof DashboardRolesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/restaurant/': {
      id: '/dashboard/restaurant/'
      path: '/restaurant'
      fullPath: '/dashboard/restaurant/'
      preLoaderRoute: typeof DashboardRestaurantIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/dishes/': {
      id: '/dashboard/dishes/'
      path: '/dishes'
      fullPath: '/dashboard/dishes/'
      preLoaderRoute: typeof DashboardDishesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/auth/better-auth': {
      id: '/_public/auth/better-auth'
      path: '/auth/better-auth'
      fullPath: '/auth/better-auth'
      preLoaderRoute: typeof PublicAuthBetterAuthRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicAuthBetterAuthRoute: typeof PublicAuthBetterAuthRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicAuthBetterAuthRoute: PublicAuthBetterAuthRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDishesIndexRoute: typeof DashboardDishesIndexRoute
  DashboardRestaurantIndexRoute: typeof DashboardRestaurantIndexRoute
  DashboardRolesIndexRoute: typeof DashboardRolesIndexRoute
  DashboardSalesIndexRoute: typeof DashboardSalesIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDishesIndexRoute: DashboardDishesIndexRoute,
  DashboardRestaurantIndexRoute: DashboardRestaurantIndexRoute,
  DashboardRolesIndexRoute: DashboardRolesIndexRoute,
  DashboardSalesIndexRoute: DashboardSalesIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoTableRoute: DemoTableRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
